apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbookapp-deployment
  lebals:
    name: guestbookapp-deployment
    app: guest-book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: guestbook-webapp-pod
      app: guest-book-app
  tamplate:
    metadata:
      name: guestbook-webapp-pod
      labels:
        name: guestbook-webapp-pod
        app: guest-book-app
    spec:
      containers:
        - name: guestbook-app
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
