apiVersion: v1
kind: Pod
metadata:
  name: guestbook-webapp-pod
  labels:
    name: guestbook-webapp-pod
    app: guest-book-app
spec:
  containers:
    - name: guestbook-app
      image: gcr.io/google-samples/gb-frontend:v4
      ports:
        - containerPort: 80
