apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: Guest-Book-app
spec:
  ports:
    - port: 6379
      targetport: 6379
  selector:
    name: redis-pod
    app: Guest-Book-app
