apiVersion: v1
kind: pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: Guest-Book-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379